
from tkinter import*
r=Tk()
r.geometry("700x700")
fname=Label(r,text="Enter the first name")
fname.grid(row=0,column=0)
lname=Label(r,text="Enter the second name")
lname.grid(row=1,column=0)
age=Label(r,text="Enter your age")
age.grid(row=2,column=0)
blood=Label(r,text="Enter your blood group")
blood.grid(row=3,column=0)
father=Label(r,text="Enter your father's name")
father.grid(row=4,column=0)
mother=Label(r,text="Enter your mother's name")
mother.grid(row=5,column=0)
phone=Label(r,text="Enter your phone number")
phone.grid(row=6,column=0)
place=Label(r,text="Enter your place")
place.grid(row=7,column=0)
e1=Entry(r)
e1.grid(row=0,column=1)
e2=Entry(r)
e2.grid(row=1,column=1)
e3=Entry(r)
e3.grid(row=2,column=1)
e4=Entry(r)
e4.grid(row=3,column=1)
e5=Entry(r)
e5.grid(row=4,column=1)
e6=Entry(r)
e6.grid(row=5,column=1)
e7=Entry(r)
e7.grid(row=6,column=1)
e8=Entry(r)
e8.grid(row=7,column=1)
def submit():
    fname=e1.get()
    lname=e2.get()
    age=e3.get()
    blood=e4.get()
    father=e5.get()
    mother=e6.get()
    phone=e7.get()
    place=e8.get()
    submit_button=Button(r,text="Submit",command=submit)
    submit_button.grid(row=8,column=1)
    f=open("application_data.txt", "a")
    f.write("\n")
    f.write(f"First Name: {fname}\n")
    f.write(f"Last Name: {lname}\n")
    f.write(f"Age: {age}\n")
    f.write(f"Blood Group: {blood}\n")
    f.write(f"Father's Name: {father}\n")
    f.write(f"Mother's Name: {mother}\n")
    f.write(f"Phone Number: {phone}\n")
    f.write(f"Place: {place}\n")
    print("Account created!\n")
    f.close()
submit_button=Button(r,text="Submit",command=submit)
submit_button.grid(row=8,column=1)
r.mainloop()
