from tkinter import*
r=Tk()
r.geometry("500x700")
r.title("login box")
r.configure(bg="#4d7095")
# header_frame
header_frame=Label(r,text="STUDENT REGISTER FORM",font=("Arial", 20, "bold"),bg="#339FB8",fg="white")
header_frame.place(x=60,y=7,width=380)
# Footer Frame
footer_frame = Frame(r,bg="#3399ff",height=50)
footer_frame.pack(side='bottom',fill='x')
Label(footer_frame, text="© 2025 MyApp. All rights reserved.", bg="#3399ff", fg="white", font=("Arial", 10)).place(x=150, y=15)
# Main Form Frame
form_frame = Frame(r, bg="#ffffff",highlightbackground="#cccccc", highlightthickness=1)
form_frame.place(x=30, y=65, width=440, height=540)
name=Label(r,text="Name",bg="#ffffff")
name.place(x=50,y=80)
email=Label(r,text="Email",bg="#ffffff")
email.place(x=50,y=120)
password=Label(r,text="Password",bg="#ffffff")
password.place(x=50,y=160)
phone=Label(r,text="phone number",bg="#ffffff")
phone.place(x=50,y=200)
e1=Entry(r)
e1.place(x=170,y=80,width=175)
e2=Entry(r)
e2.place(x=170,y=120,width=175)
e3=Entry(width=40,show="*")
e3.place(x=170,y=160,width=175,)
e4=Entry(r)
e4.place(x=170,y=200,width=175)
def submit():
    name=e1.get()
    email=e2.get()
    password=e3.get()
    phone=e4.get()
    if not name or not email or not password or not phone:
        print("incomplete","Please fill all the fields")
        return
    b=Button(r,text="Submit",command=submit)
    b.place(x=150,y=250)
    f=open("app.txt", "a")
    f.write("\n")
    f.write(f" Name: {name}\n")
    f.write(f"email:{email}\n")
    f.write(f"password: {password}\n")
    f.write(f"Phone Number: {phone}\n")
    print("Account created!\n")
b=Button(r,text="Submit",bg="#3399ff",command=submit)
b.place(x=150,y=250)
r.mainloop()
